### ISSUE TITLE
`with` option does not accept map as params

### ISSUE THREAD

**Issue by skydread1** [robertluo/pullable#21]
## Problem

We would expect
```clojure
(pull/run  '{:a (?a :with [{:p 3}])} {:a identity})
```
to return
```clojure
[{:a {:p 3}} {'?a {:p 3}}]
```
Instead, it throws the following error:
```clojure
java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.AFunction$1
```

Also How can I pass params to the function AND fetch a inner key?

In the example above, how can I get `:p` that is part of the `with` option param `{:p 3}`

## Explanation

The problem comes from the function `query/->query` that `postwalk` the params as well.
So for instance:
```clojure
(query/->query identity '{:a (?a :with [{:param 3}])})
```
returns
```clojure
[:vec
 ([:named
   [:deco [:fn :a] ((:with [:seq [:vec ([:filter [:fn :param] 3])]]))]
   ?a])]
```
and not
```clojure
[:vec
 [[:named
  [:deco [:fn :a] [[:with [{:param 3]]]]
  '?a]]]
```

Same observation for the `:not-found` option, not found can not contain a map as for now.

**Comment by robertluo** [comment]
fixed at #25
